GET http://localhost:3001/sales/1
# content-type: application/json

# {
#     "total_price": 20.20,
#     "delivery_address": "Trybe",
#     "delivery_number": 60,
#     "status": "PENDENTE",
#     "user_id": 4,
#     "seller_id": 2
# }


# GET https://example.com/comments
# content-type: application/json